data_dir: 'C:\Users\omar_pc\Desktop\replication_challenges\GNN_Rep\dataset\citeseer-doc-classification'
node_fname: 'citeseer.content'
edge_fname: 'citeseer.cites'
artefact_dir: 'C:\Users\omar_pc\Desktop\replication_challenges\GNN_Rep\artefacts'
artefact_node_dct: 'doc2node.pkl'
artefact_torch: 'torch_utils.pt'