GCN:
  depth : 1
  in_dim : 3703
  hid_dim :
    - 128
    - 256
    - 512
    - 1024
  out_dim : 6
  drop_rate : 
    - 0.1
    - 0.2
    - 0.5

OPT:
  lr: 0.01
  weight_decay: 0.0005

Pipe:
  epochs: 30